config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls', namespace='portfolio'))
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.index, name='index'),
    path('certifications/', views.certifications, name='certifications'),
    path('certifications/<certification_id>', views.certification, name='certification'),
    path('projects/', views.projects, name='projects'),
    path('projects/<project_id>', views.project, name='project'),
    path('skills/<skill_id>', views.skill, name='skill'),
]

categories/models.py
from django.db import models


class ProjectCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Project categories'

    def __str__(self):
        return self.name


class SkillCategory(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Skill categories'

    def __str__(self):
        return self.name

portfolio/models.py
from django.db import models
from datetime import date
from django.core.validators import FileExtensionValidator
from dateutil.relativedelta import relativedelta
from pdf2image import convert_from_path
from django.dispatch import receiver
from categories.models import ProjectCategory, SkillCategory


class Certification(models.Model):
    id = models.CharField(max_length=50, primary_key=True)
    title = models.CharField(max_length=200)
    date_completed = models.DateField()
    file = models.FileField(upload_to='static/media', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    cover_image = models.ImageField(blank=True)

    def __str__(self):
        return self.title


@receiver(models.signals.post_save, sender=Certification)
def extract_cover(sender, instance, created, *args, **kwargs):
    if created:
        pdf = instance.file
        cover = convert_from_path(str(pdf), 100)
        cover = cover[0]
        cover_name = str(pdf)[12:-4]
        cover.save('static/images'+cover_name+".jpg", 'JPEG')

        instance.cover_image = 'static/images'+cover_name+".jpg"
        instance.save()


class Project(models.Model):
    id = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=200)
    category = models.ForeignKey(ProjectCategory, on_delete=models.CASCADE)
    description = models.TextField()
    date_completed = models.DateField()
    work_in_progress = models.BooleanField(default=False)
    cover_image = models.ImageField(upload_to='static/images', blank=True)
    dark_cover_image = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Skill(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE)
    description = models.TextField()
    date_started = models.DateField()

    def get_time(self):
        difference = relativedelta(date.today(), self.date_started)
        years = difference.years
        months = difference.months
        if years != 0:
            if years == 1:
                if months >= 6:
                    return "year and a half"
                return "%s year" % years
            else:
                if months >= 6:
                    return "%s years and a half" % years
                return "%s years" % years
        elif months != 0:
            if months == 1:
                return "%s month" % months
            else:
                return "%s months" % months
        else:
            return "less than a month"

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    number = models.CharField(_('number'), max_length=9, blank=True)
    show_number = models.BooleanField(default=False)
    profile_photo = models.ImageField(upload_to='static/images', blank=True)
    about_me = models.TextField(blank=True)
    social_media = models.CharField(_('social media'), max_length=200, blank=True)
    show_social_media = models.BooleanField(default=False)
    repository = models.CharField(_('repository'), max_length=200, blank=True)
    show_repository = models.BooleanField(default=False)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def get_pseudonym(self):
        """
        Returns the pseudonym for the user - First letter of the name and surname, for example pseudonym of Bob Moses
        be 'bmoses'
        """
        pseudonym = ('%.1s%s' % (self.first_name, self.last_name))
        return pseudonym.lower()

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'number', 'profile_photo')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'number', 'profile_photo')

categories/views.py
from django.shortcuts import render

# Create your views here.

portfolio/views.py
from django.http import FileResponse, Http404
from django.shortcuts import render
from .models import Certification, Skill, Project
from users.models import CustomUser as User


def index(request):
    bio = User.objects.get(id=1)
    skills = Skill.objects.order_by('name')
    context = {'bio': bio, 'skills': skills}
    return render(request, 'portfolio/index.html', context)


def certifications(request):
    certifications = Certification.objects.order_by('-date_completed')
    context = {'certifications': certifications}
    return render(request, 'portfolio/certifications.html', context)


def certification(request, certification_id):
    try:
        certification = Certification.objects.get(id=certification_id)
        file = str(certification.file)
        return FileResponse(open(file, 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()


def projects(request):
    projects = Project.objects.order_by('date_completed')
    context = {'projects': projects}
    return render(request, 'portfolio/projects.html', context)


def project(request, project_id):
    project = Project.objects.get(id=project_id)
    context = {'project': project}
    return render(request, 'portfolio/project.html', context)


def skill(request, skill_id):
    skill = Skill.objects.get(id=skill_id)
    context = {'skill': skill}
    return render(request, 'portfolio/skill.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<html>
  <head>
    <title>A.M. Skills</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.svg' %}">
  </head>
  <body>
    <nav>
    <div id="menu">
      <a href="{% url 'portfolio:index' %}"><h3>A.M. Skills</h3></a>
      <a href="{% url 'portfolio:certifications' %}"><h4>Certifications</h4></a>
      <a href="{% url 'portfolio:projects' %}"><h4>Projects</h4></a>
    </div>
    <div id="user_panel">
      {% if user.is_staff %}
      <a href="{% url 'admin:index' %}"><h4>Admin Panel</h4></a>
      {% endif %}
    </div>
    </nav>
    {% block content %}{% endblock content %}
    <footer>
      <div id="box_footer"></div>
      <div id="box_footer">
        <div class="wrapper" id="images">
          <div id="logo"></div>
            <img id="logo" src="../static/images/python.png">
            <img id="logo" src="../static/images/django.png">
            <img id="logo" src="../static/images/heroku.png">
          <div id="logo"></div>
        </div>
        <div id="made_with_love">
          <p>Made by amalcew with
          <span class="red">❤</span> in
          <a href="https://www.python.org/" target="_blank"><span class="yellow underline">Python</span></a>,
          <a href="https://www.djangoproject.com/" target="_blank"><span class="green underline">Django</span></a> and
          <a href="https://www.heroku.com/" target="_blank"><span class="purple underline">Heroku</span></a></p>
        </div>
      </div>
      <div id="box_footer"></div>
    </footer>
  </body>
</html>

templates/portfolio/certifications.html
{% extends "base.html" %}
{% block content %}
<html>
    <body>
        <header></header>
        <main>
          <div class="wrapper_center"><h1>Certifications</h1></div>
          <div id="tiles">
            {% for certification in certifications %}
            <a href="{% url 'portfolio:certification' certification.id %}">
              <div id="tile">
                {% if certification.cover_image %}
                <img src="/{{ certification.cover_image }}">
                {% endif %}
                <h3>{{ certification.title }}</h3>
              </div>
            </a>
            {% endfor %}
          </div>
        </main>
    </body>
</html>
{% endblock content %}

templates/portfolio/index.html
{% extends "base.html" %}
{% block content %}
<html>
    <body>
        <header></header>
        <main>
          <div class="wrapper">
            <div id="box_picture">
              {% if bio.profile_photo %}
              <img id="profile_picture" src="{{ bio.profile_photo }}">
              {% endif %}
              <div id="contact">
                <h1>Contact</h1>
                <p><span class="green">E-mail: </span>{{ bio.email }}</p>
                {% if bio.show_number %}
                <p><span class="green">Telephone number: </span>{{ bio.number }}</p>
                {% endif %}
                <h3>Links</h3>
                {% if bio.show_social_media %}
                <p><span class="green">Social media: </span><a href="https://{{ bio.social_media }}" target="_blank"><span class="underline black">{{ bio.social_media }}</span></a>
                {% endif %}
                {% if bio.show_repository %}
                <p><span class="green">Repository: </span><a href="https://{{ bio.repository }}" target="_blank"><span class="underline black">{{ bio.repository }}</span></a>
                {% endif %}

                <h1>Skills</h1>
                {% for skill in skills %}
                × <a href="{% url 'portfolio:skill' skill.id %}"><span class="green underline">{{ skill.name }}</span></a>
                {% endfor %}
              </div>
            </div>
            <div id="box_about_me">
              <div id="about_me">
                {% if bio.about_me %}
                <div class="wrapper_center"><h1>About me</h1></div>
                <p>{% autoescape off %}{{ bio.about_me }}{% endautoescape %}</p>
                {% endif %}
              </div>
            </div>
          </div>
        </main>
    </body>
</html>
{% endblock content %}

templates/portfolio/project.html
{% extends "base.html" %}
{% block content %}
<html>
    <body>
        <header>
          {% if project.cover_image %}
          <img src="/{{ project.cover_image }}">
          {% endif %}
        </header>
        <main>
          <div id="description">
            <div class="wrapper_center"><h1>{{ project.name }}</h1></div>
            <div class="wrapper">
              <div id="entry_category">
              <h4>{{ project.category }}</h4>
              </div>
              <div  id="entry_date_completed">
                {% if not project.work_in_progress %}
                <pre>Project completed: </pre>
                <h4>{{ project.date_completed }}</h4>
                {% else %}
                <h4>Work in progress</h4>
                {% endif %}
              </div>
            </div>
            <p>{{ project.description }}</p>
          </div>
        </main>
    </body>
</html>
{% endblock content %}

templates/portfolio/projects.html
{% extends "base.html" %}
{% block content %}
<html>
    <body>
        <header></header>
        <main>
          <div class="wrapper">
            <div id="tiles-column">
              <div class="wrapper_center"><h1>Work in progress</h1></div>
              {% for project in projects %}
                  {% if project.work_in_progress %}
                  <a href="{% url 'portfolio:project' project.id %}">
                    <div id="tile-column">
                      {% if project.cover_image %}
                      <img src="/{{ project.cover_image }}">
                      {% endif %}
                      <h3>{{ project.name }}</h3>
                    </div>
                  </a>
                  {% endif %}
              {% endfor %}
            </div>
            <div id="tiles-column">
              <div class="wrapper_center"><h1>Projects</h1></div>
              {% for project in projects %}
                  {% if not project.work_in_progress %}
                  <a href="{% url 'portfolio:project' project.id %}">
                    <div id="tile-column">
                      {% if project.cover_image %}
                      <img src="/{{ project.cover_image }}">
                      {% endif %}
                      {% if project.dark_cover_image %}
                      <h3><span class="dark_green">{{ project.name }}</span></h3>
                      {% else %}
                      <h3>{{ project.name }}</h3>
                      {% endif %}
                    </div>
                  </a>
                  {% endif %}
              {% endfor %}
            </div>
          </div>
        </main>
    </body>
</html>
{% endblock content %}

templates/portfolio/skill.html
{% extends "base.html" %}
{% block content %}
<html>
    <body>
        <header></header>
        <main>
          <div id="description-narrow">
            <div class="wrapper_center"><h1>{{ skill.name }}</h1></div>
            <div class="wrapper">
              <div id="entry_category">
              <h4>{{ skill.category }}</h4>
              </div>
              <div  id="entry_date_completed">
                <pre>Skill known for </pre>
                <h4>{{ skill.get_time }}</h4>
              </div>
            </div>
            <p>{{ skill.description }}</p>
          </div>
        </main>
    </body>
</html>
{% endblock content %}